name: artifacts
on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: create a file
        run: echo "Hello world" > file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: file.txt
          
  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact  

          // add step tp read file.txt
      - name: Read file
        run: cat file.txt