name: My First Workflow
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello, GitHub Actions!"
      
      - name: Print bye
        run: echo "Bye, GitHub Actions!"
      
  say-2nd-message:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Print 2nd Message
        run: echo "This is the second message!"